# Question 1
```
What's the version of NumPy that you installed?

You can get the version information using the __version__ field:

np.__version__
```

In [1]:
import numpy as np 
import pandas as pd
import os

In [2]:
np.__version__

'1.23.5'

In [3]:
if not os.path.isfile("data.csv"):
    !wget "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"

## Question 2
```
How many records are in the dataset?

Here you need to specify the number of rows.

16
6572
11914
18990
```

In [4]:
price_df = pd.read_csv("data.csv")
price_df.shape[0]

11914

## Question 3
```
Who are the most frequent car manufacturers (top-3) according to the dataset?

Chevrolet, Volkswagen, Toyota
Chevrolet, Ford, Toyota
Ford, Volkswagen, Toyota
Chevrolet, Ford, Volkswagen
```

In [5]:
make_counts = price_df.Make.value_counts()
top_three = make_counts[:3]

', '.join(top_three.index)

'Chevrolet, Ford, Volkswagen'

## Question 4
```
What's the number of unique Audi car models in the dataset?

3
16
26
34
```

In [6]:
price_df[price_df.Make == "Audi"].Model.nunique()

34

## Question 5
```
How many columns in the dataset have missing values?

5
6
7
8
```

In [7]:
sum(price_df.isna().sum() > 0)

5

## Question 6
1. Find the median value of "Engine Cylinders" column in the dataset.
1. Next, calculate the most frequent value of the same "Engine Cylinders".
1. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
1. Now, calculate the median value of "Engine Cylinders" once again.

In [8]:
# 1
engine_cylinder_median = price_df["Engine Cylinders"].median()
engine_cylinder_median

6.0

In [9]:
# 2
engine_cylinder_most_freq_value = price_df["Engine Cylinders"].value_counts().index[0]
engine_cylinder_most_freq_value

4.0

In [10]:
# 3
price_df["Engine Cylinders"].fillna(engine_cylinder_most_freq_value, inplace=True)
price_df["Engine Cylinders"].isna().sum()

0

In [11]:
# 4
"No" if price_df["Engine Cylinders"].median() == engine_cylinder_median else "Yes"

'No'

## Question 7
1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Compute the inverse of XTX.
7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the value of the first element of w?

In [12]:
lotus_df = price_df[price_df.Make == 'Lotus']
lotus_df.head()

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

In [13]:
lotus_hp_cylinder_df = lotus_df[["Engine HP", "Engine Cylinders"]]
lotus_hp_cylinder_df

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [14]:
lotus_hp_cylinder_unique_df = lotus_hp_cylinder_df.drop_duplicates()
lotus_hp_cylinder_unique_df

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [15]:
X = lotus_hp_cylinder_unique_df.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [16]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [17]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [18]:
XTX_inv.dot(XTX)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [19]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [20]:
XTX_dot_XT = XTX_inv.dot(X.T)
w = XTX_dot_XT.dot(y)
w[0]

4.594944810094579